### ISSUE TITLE
Unclear that files on usaid.gov/data correlate to the Foreign Assistance Dashboard

### ISSUE THREAD

**Issue by Krista-Nuams** [USAID/USAID-Data-Services#11]
This ticket relates to https://github.com/USAID/Feedback/issues/8. 
There are two issues that still remain:
1) The links to the XML files listed are still returning 404 errors. The previous ticket response said that Foreign Assistance data can be found on http://www.foreignassistance.gov/, but that is not clear to a visitor on usaid.gov/data. The files with 404 errors could either be removed or the links could be corrected to bring a user to the appropriate data.

2) It is unclear which data on the FAD correlates to listed data resources on usaid.gov/data that are returning 404 errors. For example: I do not see a file called "Foreign Assistance Dashboard, East Asia Regional"  on http://www.foreignassistance.gov/. By doing a general keyword search, I found there are 260 files related to the "East Asia Region" but there is no way of knowing that all those files were the intended set of data to be posted on /data or whether that XML file was originally a subset of those 260 files that came up in a keyword search.

**Comment by jksmith6** [comment]
Good morning @Krista-Nuams,

Amarsili’s feedback and corrections provided the appropriate fix concerning your inquiry. Thank you for all of your feedback and contributions.

Kind regards,
The USAID Data Services Team

Closed #11
