### ISSUE TITLE
Expose API for map.usaid.gov

### ISSUE THREAD

**Issue by markbrough** [USAID/USAID-Data-Services#2]
Make it easier to access the data behind http://map.usaid.gov; preferably with some brief documentation about how to use the API, what data is available in it, and perhaps some information about the quality of the data if that is appropriate (so people are aware before drawing strong conclusions from the data).

It would be good to use standards to expose the data, e.g.:
- use USAID's real internal project IDs (where available), and not just the artificial one that you see in the URL
- use ISO 3166 alpha-2 country codes, e.g. http://datadev.aidinfolabs.org/data/codelist/Country
- use CRS sector codes if possible; otherwise perhaps provide a spreadsheet mapping between internal sector codes and CRS codes?
- use IATI / AidData / World Bank methodology for geo-coded data (NB, there are some discussions about adjusting this)
- in the future (and obviously depending on internal processes), conformance with [IATI Standard](http://iatistandard.org) would be a good objective to aim for.

**Comment by jksmith6** [comment]
Closes #2
