### ISSUE TITLE
DHS Data API

### ISSUE THREAD

**Issue by jdweaver** [USAID/USAID-Data-Services#22]
Series of questions (let me know if there is a different format for posting these questions) 
1) Is there a list for DHS survey data that shows the existing countries and years we can query with the API? Similarly, is there a list that shows the DHS data sets that will be added? 

2) Will the row limits for the API be increased in the future? The use case I am thinking of is needing to look at trends over time for multiple countries for a particular set of indicators. 

thanks!

**Comment by RoyIMiller** [comment]
1.	The best resource for learning about the DHS API is the API website-- http://api.dhsprogram.com/.  The best resource for learning more about the underlying data that the API accesses is the DHS Program's website--www.dhsprogram.com.  Note-- the API uses the same indicator-level data provided through STATcompiler, which is an on-line tool that allows users to build tables, charts, graphs with DHS data.  By exploring STATcompiler, one can see which countries have DHS data, how many DHS have been conducted by country, which indicators are available, and more.  In terms of new DHS data to be added, this list can be found on the DHS Program website on the survey search page, here-- http://www.dhsprogram.com/What-We-Do/Survey-Search.cfm.  Searching by "recently completed" provides a list of surveys for which data will soon be added while searching for "ongoing" provides a list of surveys that are in process.
2.	To learn more about row limits, see the advanced queries page on the API website-- http://api.dhsprogram.com/#/api-advancedqueries.cfm.  As currently designed, the DHS API allows for trends across time and country for sets of indicators.  If you are still experiencing a problem, please shoot a note to api@dhsprogram.com.  The folks managing the API are generally quite quick to respond.

**Comment by MorganDaniels** [comment]
Closes #22

**Comment by jksmith6** [comment]
>close
