### ISSUE TITLE
Open Data definition in the ADS

### ISSUE THREAD

**Issue by KatataK** [USAID/USAID-Data-Services#24]
Can one please be added so that any program designers, CORs, implementers, and others understand and are accountable to what is required in ADS579.

**Comment by wuhland** [comment]
Do you mean a definition for what is Open Data? Would that differ from the definition of principles used to describe Open Data listed in the OMB Open Data Policy M-13-13 and listed [here] (https://project-open-data.cio.gov/principles/). 

Or do you mean more guidance around what datasets should be added to DDL? If so I +1, there are a number of overlapping policies that affect this and it would be great if some kind of comprehensive resource was pulled together with the key points from each.
