### ISSUE TITLE
ADS in machine-readable & searchable format

### ISSUE THREAD

**Issue by KatataK** [USAID/USAID-Data-Services#25]
The ADS- USAID's operational strategy- requires independently downloading separate PDFs for each section.  Please issue this as a machine-readable open format.  External volunteers can then run analysis and develop APIs that can benefit USAID staff, partners, and grant-seekers to highlight any significant changes relevant to their work.  In addition donor coordination will be improved by more effectively comparing and syncing definitions, program design requirements, indicators as a metric of a project's success... etc.

**Comment by sheth7** [comment]
I agree. Textifying the data is too much hassle especially given that all reports etc are uniquely structured. 

KatataK - do you have any updates on this?

**Comment by MorganDaniels** [comment]
Thanks for your question. USAID has no plans to make a machine readable ADS. However all ADS documents are 508 compliant making them accessible to people with disabilities.
