### ISSUE TITLE
API for submitting data to Open Data to DDL?

### ISSUE THREAD

**Issue by claar** [USAID/USAID-Data-Services#26]
Are there any plans to offer an API for submitting data to the DDL, rather than just querying existing data?

**Comment by bpushed** [comment]
Greetings Ben -- While a decision has not yet been made, this is something we are considering for upgrades to the DDL planned in 2016 and has already been discussed in planning meetings.  At bare minimum, we will keep this logged on our requirements list for future upgrades.

**Comment by opleban** [comment]
@claar You can find information on the various methods for publishing data to the Socrata platform on our developers' page (https://dev.socrata.com/publishers/)
