### ISSUE TITLE
Request for Philippines/E-PESO datasets

### ISSUE THREAD

**Issue by bpccacnio** [USAID/USAID-Data-Services#29]
We are students from the School of Economics at University of the Philippines, working on our undergraduate thesis about e-money, e-payments, and financial inclusion in our country. During our research, we came across the "2016 Philippine Individual Payments Baseline Study" by USAID. 

We would like to ask if we may access the data from your 'E-PESO Individual Payments Baseline Survey', and other datasets you may have on the topic.

Any help or assistance would be greatly appreciated.

Thank you!

**Comment by jksmith6** [comment]
Good afternoon to you all. 

Thank you for your inquiry. We are delighted to help in any way possible. First of all, we want to apologize for our long period of inactivity. As you might know, the Development Data Library (DDL) was recently launched on a new platform on November 13, 2018. Our team is working to ensure a quick response to all open questions regarding USAID open data on GitHub, and a swift response to all new questions as they are posted. 

In regards to your request, the “2016 Philippine Individual Payments Baseline Study” is still in the data review process and as a result, the dataset must remain restricted until it has been cleared. We encourage you to continue checking back on the new Development Data Library (DDL) to see when this dataset is made publicly available.

The USAID Data Services team is looking forward to remaining engaged and active with this community in the future. We hope that you will continue to turn to the DDL for your future research endeavors. If you have any additional questions, feel free to contact our team directly at dataservices@usaid.gov.

Kind regards,
The USAID Data Services team 

Closed #29

**Comment by christophermurphy** [comment]
Has the 2016 Philippine Individual Payments Baseline Study been cleared, yet?

**Comment by MorganDaniels** [comment]
Unfortunately, it has not.  There are some issues with the study documentation that still must be resolved prior to clearance.  We have re-initiated the conversation with the partner and will update here once we know more.  Our apologies for the delay.

Kind regards,
USAID Data Services Team
dataservices@usaid.gov
