### ISSUE TITLE
Time-out period

### ISSUE THREAD

**Issue by zoltanmilic** [USAID/USAID-Data-Services#31]
Hi. The new DDL platform does not detect period of inactivity, but has a set timer. I've been editing meta-data for questionnaire columns; been cut-off; and no earlier changes had been saved. Frustrating. Can you change that setting pls?

**Comment by devanalysis** [comment]
Hi Zoltan, I completely understand your frustration—this is something the DDL team has been experiencing as well, as we continue to work in the platform every day.

However, in accordance with government policy (the [DHS Sensitive Systems Handbook](https://www.dhs.gov/sites/default/files/publications/4300A%20Sensitive-Systems-Handbook-v12_0-508Cs.pdf) section 5.2.2), the platform will automatically log out after 20 minutes. So, while some platform features might work differently under this policy, it is ultimately designed to make sure you, your data, and the DDL are kept safe and secure.

At the bottom of every page of the data asset and dataset registration forms (except the Certification), there is a "Save Draft" button, which will allow you to save the form and continue from there. Drafts can then be accessed at any time by clicking on the "person" icon in the far top right of your screen, and selecting "My Profile".

Thank you for reaching out to us; I hope this helped!

Robin, USAID Data Services
