### ISSUE TITLE
Request for EGRA microdata

### ISSUE THREAD

**Issue by eldafani** [USAID/USAID-Data-Services#32]
Hello,

I am not able to submit a data request (https://data.usaid.gov/access-request). The alert message reads "Please provide information for all required fields to ensure that we are able to properly assess your request.". However, all required fields are complete. I am trying to request EGRA microdata underpinning assessment results reported in the barometer: https://earlygradereadingbarometer.org/.

I would greatly appreciate your advice. Thank you.

all the best,
Daniel

**Comment by MorganDaniels** [comment]
Hello Daniel,
Thank you for your message.  While the Development Data Library has received several submissions of country-specific EGRA data, we have not received the complete microdata underpinning the site https://earlygradereadingbarometer.org/.  Our team will reach out to RTI, the organization responsible for the Barometer, to request a submission of the microdata.  I will follow up with you via your Gmail address to update you on the process.
Best,
Morgan

**Comment by eldafani** [comment]
Thank you very much!
Daniel
