### ISSUE TITLE
DLL Account Error

### ISSUE THREAD

**Issue by Sudar-Theepan** [USAID/USAID-Data-Services#33]
Hi, 
The following error I received while I am login in through login.gov. I have a DIS account for the same credentials, it works perfectly. But the DLL is not. I am a new user for DLL. 

{
  "code" : "USER.DISABLED",
  "error" : true,
  "message" : "User has been disabled"
}

Best, 
Theepan

**Comment by USAID-owner** [comment]
Hello Sudar,

I have reactivated your account and you should now be able to log in.

Mark
