### ISSUE TITLE
Disabled Account

### ISSUE THREAD

**Issue by akisseldiskin** [USAID/USAID-Data-Services#34]
I am following the instructions for reactivating my data.usaid.gov account by clicking Sign in with @[usaid.gov](http://usaid.gov/) on the platform. However, I am still getting an error. 

{
  "code" : "USER.DISABLED",
  "error" : true,
  "message" : "User has been disabled"
}

Thank you for any help you can provide.

**Comment by MorganDaniels** [comment]
Good morning,
DDL accounts that have not been accessed in the last 90 days are automatically disabled in accordance with system security requirements.  The best way to have your account reactivated by our administrators is via email to dataservicesrequest@usaid.gov.  I see that you have been in touch with one of my colleagues who has reactivated your account, so I will close this ticket.  
Best wishes,
Morgan
