### ISSUE TITLE
DDL User Error

### ISSUE THREAD

**Issue by cargo-m** [USAID/USAID-Data-Services#35]
Hi,

I tried to sign in to DDL with my login.gov account, and I got the following user error:

"code" : "USER.DISABLED",
  "error" : true,
  "message" : "User has been disabled"

**Comment by USAID-owner** [comment]
Could you please give me your full name and account email address so that I
can further investigate?

Laura Hjerpe, Data Services

**Comment by MorganDaniels** [comment]
Hello cargo-m,
Please email our team at dataservicesrequest@usaid.gov for assistance- we will reactivate your account.

Best,
USAID Data Services Team
