### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by ashleybishop1** [USAID/USAID-Data-Services#37]
I already have an account but whenever I try to log in today I get this image: 

![Picture1](https://user-images.githubusercontent.com/129785124/229587941-4895d543-a7f9-4e14-be17-9c1a5e8213db.png)

**Comment by USAID-owner** [comment]
Dear Ashley,

I think this error you are seeing is what happens immediately after
attempting to clear the Login.gov portal. Data Services can only help you
once you pass the portal.  I suggest contacting Login.gov here
<https://login.gov/help/>. It could be that your login.gov account expired.

Mark
