### ISSUE TITLE
Request for Thesaurus of keywords from the DEC

### ISSUE THREAD

**Issue by KatataK** [USAID/USAID-Data-Services#6]
Emailed to opendata@usaid.gov and requested via data.gov:

https://explore.data.gov/nominate/3226
Thesaurus of keywords used to index documents included in the USAID Development Experience Clearinghouse (DEC)

**Comment by sheth7** [comment]
Hello, any updates on this decision? Thanks.

**Comment by MorganDaniels** [comment]
Hello, thank you for your question.  We are looking into this request and will respond by the end of next week with an update.

**Comment by MorganDaniels** [comment]
Hello,
We have published the DEC Thesaurus, updated for 2019, to the Development Data Library as a csv file. Feel free to [access it at this link](https://data.usaid.gov/Information-and-Communications-Technology-Services/USAID-Thesaurus-2019/abaj-3t2b).

Best,
USAID Data Services Team
