### ISSUE TITLE
data file is buried within zip file

### ISSUE THREAD

**Issue by cmurphyUSAID** [USAID/USAID-Data-Services#9]
I went to http://www.usaid.gov/developer/FTFBangladesh and downloaded the data file.

The data file and code book are buried in the folders

the csv file

> bihs_usaid_4.23.2013 > census > data > csv

the Code book

> bihs_usaid_4.23.2013 > census > document

Could these files be posted outside of the zipped file or include directions for drilling down to the content?

Also, the codebook is in pdf.

Could this be moved to an open and machine readable format?

**Comment by abbyrjones72** [comment]
I second this motion. Transparency should also include easier access to the data.

**Comment by bpushed** [comment]
USAID will be launching an entirely new platform for the Development Data Library (DDL) in 2018.  We expect the user interface for the new platform to improve the visibility of supporting documentation related to datasets.

**Comment by jksmith6** [comment]
Closes #9

**Comment by christophermurphy** [comment]
I followed the link and there is no data. The link in the "Associated Datasets" section goes to another page, and the dataset there is blank.

https://data.usaid.gov/Agriculture/Feed-the-Future-Bangladesh-Baseline-Integrated-Hou/gqdq-2zi3

**Comment by MorganDaniels** [comment]
The data may be downloaded as a zip file from the Source Link field in the record https://data.usaid.gov/Agriculture/Feed-the-Future-Bangladesh-Baseline-Integrated-Hou/gqdq-2zi3.  We have updated the description to include download instructions.
